services:
  clash-hub:
    image: ghcr.io/zhou-jian-qq/clash-hub:latest
    container_name: clash-hub
    ports:
      - "8080:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
