"""
Clash Hub 预设模板库
每个模板定义: proxy_groups, rule_providers, rules
公共基础配置 (DNS, sniffer, geodata) 由 BASE_CONFIG 提供
"""

BASE_CONFIG = {
    "mixed-port": 7897,
    "allow-lan": True,
    "mode": "rule",
    "log-level": "info",
    "unified-delay": True,
    "tcp-concurrent": True,
    "find-process-mode": "strict",
    "dns": {
        "enable": True,
        "listen": "127.0.0.1:5335",
        "use-system-hosts": False,
        "enhanced-mode": "fake-ip",
        "fake-ip-range": "198.18.0.1/16",
        "default-nameserver": ["180.76.76.76", "182.254.118.118", "8.8.8.8", "180.184.2.2"],
        "nameserver": [
            "180.76.76.76", "119.29.29.29", "180.184.1.1", "223.5.5.5", "8.8.8.8",
            "https://223.6.6.6/dns-query#h3=true", "https://dns.alidns.com/dns-query",
            "https://cloudflare-dns.com/dns-query", "https://doh.pub/dns-query",
        ],
        "fallback": [
            "https://000000.dns.nextdns.io/dns-query#h3=true", "https://dns.alidns.com/dns-query",
            "https://doh.pub/dns-query", "https://public.dns.iij.jp/dns-query",
            "https://101.101.101.101/dns-query", "https://208.67.220.220/dns-query",
            "tls://8.8.4.4", "tls://1.0.0.1:853",
            "https://cloudflare-dns.com/dns-query", "https://dns.google/dns-query",
        ],
        "fallback-filter": {
            "geoip": True,
            "ipcidr": ["240.0.0.0/4", "0.0.0.0/32", "127.0.0.1/32"],
            "domain": ["+.google.com", "+.facebook.com", "+.twitter.com", "+.youtube.com",
                       "+.xn--ngstr-lra8j.com", "+.google.cn", "+.googleapis.cn",
                       "+.googleapis.com", "+.gvt1.com"],
        },
        "fake-ip-filter": [
            "*.lan", "stun.*.*.*", "stun.*.*",
            "time.windows.com", "time.nist.gov", "time.apple.com", "time.asia.apple.com",
            "*.ntp.org.cn", "*.openwrt.pool.ntp.org",
            "time1.cloud.tencent.com", "time.ustc.edu.cn", "pool.ntp.org", "ntp.ubuntu.com",
            "ntp.aliyun.com", "ntp1.aliyun.com", "ntp2.aliyun.com", "ntp3.aliyun.com",
            "ntp4.aliyun.com", "ntp5.aliyun.com", "ntp6.aliyun.com", "ntp7.aliyun.com",
            "time1.aliyun.com", "time2.aliyun.com", "time3.aliyun.com", "time4.aliyun.com",
            "time5.aliyun.com", "time6.aliyun.com", "time7.aliyun.com", "*.time.edu.cn",
            "time1.apple.com", "time2.apple.com", "time3.apple.com", "time4.apple.com",
            "time5.apple.com", "time6.apple.com", "time7.apple.com",
            "time1.google.com", "time2.google.com", "time3.google.com", "time4.google.com",
            "music.163.com", "*.music.163.com", "*.126.net",
            "musicapi.taihe.com", "music.taihe.com",
            "songsearch.kugou.com", "trackercdn.kugou.com", "*.kuwo.cn",
            "api-jooxtt.sanook.com", "api.joox.com", "joox.com",
            "y.qq.com", "*.y.qq.com", "streamoc.music.tc.qq.com", "mobileoc.music.tc.qq.com",
            "isure.stream.qqmusic.qq.com", "dl.stream.qqmusic.qq.com",
            "aqqmusic.tc.qq.com", "amobile.music.tc.qq.com",
            "*.xiami.com", "*.music.migu.cn", "music.migu.cn",
            "*.msftconnecttest.com", "*.msftncsi.com", "localhost.ptlogin2.qq.com",
            "*.*.*.srv.nintendo.net", "*.*.stun.playstation.net",
            "xbox.*.*.microsoft.com", "*.ipv6.microsoft.com", "*.*.xboxlive.com",
            "speedtest.cros.wr.pvp.net",
        ],
    },
    "profile": {"store-selected": True, "store-fake-ip": False},
    "sniffer": {
        "enable": True,
        "parse-pure-ip": True,
        "sniff": {
            "HTTP": {"ports": [80, "8080-8880"], "override-destination": True},
            "QUIC": {"ports": [443, 8443]},
            "TLS": {"ports": [443, 8443]},
        },
    },
    "geodata-mode": True,
    "geo-auto-update": True,
    "geodata-loader": "standard",
    "geo-update-interval": 24,
    "geox-url": {
        "geoip": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat",
        "geosite": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat",
        "mmdb": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb",
        "asn": "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb",
    },
}


def _g(name, gtype="select", prepend=None, include_all=True, **extra):
    """proxy-group 定义快捷构造"""
    return {"name": name, "type": gtype, "prepend": prepend or [], "include_all": include_all, **extra}


def _rp(name, behavior, url_path, fmt="mrs"):
    """rule-provider 定义快捷构造"""
    base = "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo"
    return {
        "type": "http", "behavior": behavior,
        "url": f"{base}/{url_path}",
        "path": f"./ruleset/{name}.mrs",
        "interval": 86400, "format": fmt,
    }


SELECT = "🚀 节点选择"
AUTO = "⚡ 自动选择"
STD_PREPEND = [SELECT, AUTO, "DIRECT", "REJECT"]
HOME_PREPEND = ["DIRECT", "REJECT", SELECT, AUTO]

# ═══════════════════════════════════════════
# 精简版
# ═══════════════════════════════════════════
SIMPLE_GROUPS = [
    _g(SELECT, "select", [AUTO, "DIRECT", "REJECT"]),
    _g(AUTO, "url-test", [], url="https://www.gstatic.com/generate_204", interval=3600, lazy=False),
    _g("🛑 广告拦截", "select", ["REJECT", "DIRECT", SELECT], include_all=False),
    _g("🏠 私有网络", "select", HOME_PREPEND),
    _g("🔒 国内服务", "select", HOME_PREPEND),
    _g("🌍 非中国", "select", STD_PREPEND),
    _g("🐟 漏网之鱼", "select", STD_PREPEND),
]

SIMPLE_RP = {
    "category-ads-all": _rp("category-ads-all", "domain", "geosite/category-ads-all.mrs"),
    "private": _rp("private", "domain", "geosite/private.mrs"),
    "private-ip": _rp("private-ip", "ipcidr", "geoip/private.mrs"),
    "geolocation-cn": _rp("geolocation-cn", "domain", "geosite/geolocation-cn.mrs"),
    "cn-ip": _rp("cn-ip", "ipcidr", "geoip/cn.mrs"),
    "geolocation-!cn": _rp("geolocation-!cn", "domain", "geosite/geolocation-!cn.mrs"),
    "cn": _rp("cn", "domain", "geosite/cn.mrs"),
}

SIMPLE_RULES = [
    "RULE-SET,category-ads-all,🛑 广告拦截",
    "RULE-SET,private,🏠 私有网络",
    "RULE-SET,private-ip,🏠 私有网络,no-resolve",
    "RULE-SET,geolocation-cn,🔒 国内服务",
    "RULE-SET,cn-ip,🔒 国内服务,no-resolve",
    "RULE-SET,geolocation-!cn,🌍 非中国",
    "RULE-SET,cn,🔒 国内服务",
    "MATCH,🐟 漏网之鱼",
]

# ═══════════════════════════════════════════
# 标准版
# ═══════════════════════════════════════════
STANDARD_GROUPS = [
    _g(SELECT, "select", [AUTO, "DIRECT", "REJECT"]),
    _g(AUTO, "url-test", [], url="https://www.gstatic.com/generate_204", interval=3600, lazy=False),
    _g("🛑 广告拦截", "select", ["REJECT", "DIRECT", SELECT], include_all=False),
    _g("🤖 AI 服务", "select", STD_PREPEND),
    _g("📹 油管视频", "select", STD_PREPEND),
    _g("🔍 谷歌服务", "select", STD_PREPEND),
    _g("Ⓜ️ 微软服务", "select", STD_PREPEND),
    _g("🍏 苹果服务", "select", STD_PREPEND),
    _g("📲 电报消息", "select", STD_PREPEND),
    _g("🐱 代码托管", "select", STD_PREPEND),
    _g("🏠 私有网络", "select", HOME_PREPEND),
    _g("🔒 国内服务", "select", HOME_PREPEND),
    _g("🌍 非中国", "select", STD_PREPEND),
    _g("🐟 漏网之鱼", "select", STD_PREPEND),
]

STANDARD_RP = {
    **SIMPLE_RP,
    "category-ai-chat-!cn": _rp("category-ai-chat-!cn", "domain", "geosite/category-ai-chat-!cn.mrs"),
    "openai": _rp("openai", "domain", "geosite/openai.mrs"),
    "anthropic": _rp("anthropic", "domain", "geosite/anthropic.mrs"),
    "youtube": _rp("youtube", "domain", "geosite/youtube.mrs"),
    "google": _rp("google", "domain", "geosite/google.mrs"),
    "google-ip": _rp("google-ip", "ipcidr", "geoip/google.mrs"),
    "microsoft": _rp("microsoft", "domain", "geosite/microsoft.mrs"),
    "onedrive": _rp("onedrive", "domain", "geosite/onedrive.mrs"),
    "apple": _rp("apple", "domain", "geosite/apple.mrs"),
    "icloud": _rp("icloud", "domain", "geosite/icloud.mrs"),
    "telegram": _rp("telegram", "domain", "geosite/telegram.mrs"),
    "telegram-ip": _rp("telegram-ip", "ipcidr", "geoip/telegram.mrs"),
    "github": _rp("github", "domain", "geosite/github.mrs"),
    "gitlab": _rp("gitlab", "domain", "geosite/gitlab.mrs"),
    "atlassian": _rp("atlassian", "domain", "geosite/atlassian.mrs"),
}

STANDARD_RULES = [
    "RULE-SET,category-ads-all,🛑 广告拦截",
    "RULE-SET,category-ai-chat-!cn,🤖 AI 服务",
    "RULE-SET,openai,🤖 AI 服务",
    "RULE-SET,anthropic,🤖 AI 服务",
    "RULE-SET,youtube,📹 油管视频",
    "RULE-SET,google,🔍 谷歌服务",
    "RULE-SET,google-ip,🔍 谷歌服务,no-resolve",
    "RULE-SET,private,🏠 私有网络",
    "RULE-SET,private-ip,🏠 私有网络,no-resolve",
    "RULE-SET,geolocation-cn,🔒 国内服务",
    "RULE-SET,cn-ip,🔒 国内服务,no-resolve",
    "RULE-SET,telegram,📲 电报消息",
    "RULE-SET,telegram-ip,📲 电报消息,no-resolve",
    "RULE-SET,github,🐱 代码托管",
    "RULE-SET,gitlab,🐱 代码托管",
    "RULE-SET,atlassian,🐱 代码托管",
    "RULE-SET,microsoft,Ⓜ️ 微软服务",
    "RULE-SET,onedrive,Ⓜ️ 微软服务",
    "RULE-SET,apple,🍏 苹果服务",
    "RULE-SET,icloud,🍏 苹果服务",
    "RULE-SET,geolocation-!cn,🌍 非中国",
    "RULE-SET,cn,🔒 国内服务",
    "MATCH,🐟 漏网之鱼",
]

# ═══════════════════════════════════════════
# 完整版
# ═══════════════════════════════════════════
FULL_GROUPS = [
    _g(SELECT, "select", [AUTO, "DIRECT", "REJECT"]),
    _g(AUTO, "url-test", [], url="https://www.gstatic.com/generate_204", interval=3600, lazy=False),
    _g("🛑 广告拦截", "select", ["REJECT", "DIRECT", SELECT], include_all=False),
    _g("🤖 AI 服务", "select", STD_PREPEND),
    _g("📹 油管视频", "select", STD_PREPEND),
    _g("🔍 谷歌服务", "select", STD_PREPEND),
    _g("Ⓜ️ 微软服务", "select", STD_PREPEND),
    _g("🍏 苹果服务", "select", STD_PREPEND),
    _g("📲 电报消息", "select", STD_PREPEND),
    _g("🐦 推特/X", "select", STD_PREPEND),
    _g("📘 Meta 系", "select", STD_PREPEND),
    _g("🎙️ Discord", "select", STD_PREPEND),
    _g("💬 其他社交", "select", STD_PREPEND),
    _g("🎬 奈飞", "select", STD_PREPEND),
    _g("🏰 迪士尼+", "select", STD_PREPEND),
    _g("📺 欧美流媒体", "select", STD_PREPEND),
    _g("🎌 亚洲流媒体", "select", STD_PREPEND),
    _g("🎮 Steam", "select", STD_PREPEND),
    _g("🖥️ PC 游戏", "select", STD_PREPEND),
    _g("🎯 主机游戏", "select", STD_PREPEND),
    _g("🐱 代码托管", "select", STD_PREPEND),
    _g("☁️ 云服务", "select", STD_PREPEND),
    _g("🛠️ 开发工具", "select", STD_PREPEND),
    _g("💾 网盘存储", "select", STD_PREPEND),
    _g("💳 支付平台", "select", STD_PREPEND),
    _g("₿ 加密货币", "select", STD_PREPEND),
    _g("📚 教育学术", "select", STD_PREPEND),
    _g("📰 新闻资讯", "select", STD_PREPEND),
    _g("🛒 海淘购物", "select", STD_PREPEND),
    _g("🏠 私有网络", "select", HOME_PREPEND),
    _g("🔒 国内服务", "select", HOME_PREPEND),
    _g("🌍 非中国", "select", STD_PREPEND),
    _g("🐟 漏网之鱼", "select", STD_PREPEND),
]

FULL_RP = {
    **STANDARD_RP,
    "twitter": _rp("twitter", "domain", "geosite/twitter.mrs"),
    "twitter-ip": _rp("twitter-ip", "ipcidr", "geoip/twitter.mrs"),
    "facebook": _rp("facebook", "domain", "geosite/facebook.mrs"),
    "instagram": _rp("instagram", "domain", "geosite/instagram.mrs"),
    "whatsapp": _rp("whatsapp", "domain", "geosite/whatsapp.mrs"),
    "facebook-ip": _rp("facebook-ip", "ipcidr", "geoip/facebook.mrs"),
    "discord": _rp("discord", "domain", "geosite/discord.mrs"),
    "tiktok": _rp("tiktok", "domain", "geosite/tiktok.mrs"),
    "line": _rp("line", "domain", "geosite/line.mrs"),
    "reddit": _rp("reddit", "domain", "geosite/reddit.mrs"),
    "linkedin": _rp("linkedin", "domain", "geosite/linkedin.mrs"),
    "snap": _rp("snap", "domain", "geosite/snap.mrs"),
    "pinterest": _rp("pinterest", "domain", "geosite/pinterest.mrs"),
    "tumblr": _rp("tumblr", "domain", "geosite/tumblr.mrs"),
    "netflix": _rp("netflix", "domain", "geosite/netflix.mrs"),
    "netflix-ip": _rp("netflix-ip", "ipcidr", "geoip/netflix.mrs"),
    "disney": _rp("disney", "domain", "geosite/disney.mrs"),
    "hbo": _rp("hbo", "domain", "geosite/hbo.mrs"),
    "hulu": _rp("hulu", "domain", "geosite/hulu.mrs"),
    "primevideo": _rp("primevideo", "domain", "geosite/primevideo.mrs"),
    "apple-tvplus": _rp("apple-tvplus", "domain", "geosite/apple-tvplus.mrs"),
    "spotify": _rp("spotify", "domain", "geosite/spotify.mrs"),
    "twitch": _rp("twitch", "domain", "geosite/twitch.mrs"),
    "dazn": _rp("dazn", "domain", "geosite/dazn.mrs"),
    "bahamut": _rp("bahamut", "domain", "geosite/bahamut.mrs"),
    "biliintl": _rp("biliintl", "domain", "geosite/biliintl.mrs"),
    "niconico": _rp("niconico", "domain", "geosite/niconico.mrs"),
    "abema": _rp("abema", "domain", "geosite/abema.mrs"),
    "viu": _rp("viu", "domain", "geosite/viu.mrs"),
    "kktv": _rp("kktv", "domain", "geosite/kktv.mrs"),
    "steam": _rp("steam", "domain", "geosite/steam.mrs"),
    "epicgames": _rp("epicgames", "domain", "geosite/epicgames.mrs"),
    "ea": _rp("ea", "domain", "geosite/ea.mrs"),
    "ubisoft": _rp("ubisoft", "domain", "geosite/ubisoft.mrs"),
    "blizzard": _rp("blizzard", "domain", "geosite/blizzard.mrs"),
    "gog": _rp("gog", "domain", "geosite/gog.mrs"),
    "riot": _rp("riot", "domain", "geosite/riot.mrs"),
    "playstation": _rp("playstation", "domain", "geosite/playstation.mrs"),
    "xbox": _rp("xbox", "domain", "geosite/xbox.mrs"),
    "nintendo": _rp("nintendo", "domain", "geosite/nintendo.mrs"),
    "aws": _rp("aws", "domain", "geosite/aws.mrs"),
    "azure": _rp("azure", "domain", "geosite/azure.mrs"),
    "cloudflare": _rp("cloudflare", "domain", "geosite/cloudflare.mrs"),
    "digitalocean": _rp("digitalocean", "domain", "geosite/digitalocean.mrs"),
    "vercel": _rp("vercel", "domain", "geosite/vercel.mrs"),
    "netlify": _rp("netlify", "domain", "geosite/netlify.mrs"),
    "cloudflare-ip": _rp("cloudflare-ip", "ipcidr", "geoip/cloudflare.mrs"),
    "docker": _rp("docker", "domain", "geosite/docker.mrs"),
    "npmjs": _rp("npmjs", "domain", "geosite/npmjs.mrs"),
    "jetbrains": _rp("jetbrains", "domain", "geosite/jetbrains.mrs"),
    "stackexchange": _rp("stackexchange", "domain", "geosite/stackexchange.mrs"),
    "dropbox": _rp("dropbox", "domain", "geosite/dropbox.mrs"),
    "notion": _rp("notion", "domain", "geosite/notion.mrs"),
    "paypal": _rp("paypal", "domain", "geosite/paypal.mrs"),
    "stripe": _rp("stripe", "domain", "geosite/stripe.mrs"),
    "wise": _rp("wise", "domain", "geosite/wise.mrs"),
    "binance": _rp("binance", "domain", "geosite/binance.mrs"),
    "category-scholar-!cn": _rp("category-scholar-!cn", "domain", "geosite/category-scholar-!cn.mrs"),
    "coursera": _rp("coursera", "domain", "geosite/coursera.mrs"),
    "udemy": _rp("udemy", "domain", "geosite/udemy.mrs"),
    "edx": _rp("edx", "domain", "geosite/edx.mrs"),
    "khanacademy": _rp("khanacademy", "domain", "geosite/khanacademy.mrs"),
    "wikimedia": _rp("wikimedia", "domain", "geosite/wikimedia.mrs"),
    "bbc": _rp("bbc", "domain", "geosite/bbc.mrs"),
    "cnn": _rp("cnn", "domain", "geosite/cnn.mrs"),
    "nytimes": _rp("nytimes", "domain", "geosite/nytimes.mrs"),
    "wsj": _rp("wsj", "domain", "geosite/wsj.mrs"),
    "bloomberg": _rp("bloomberg", "domain", "geosite/bloomberg.mrs"),
    "amazon": _rp("amazon", "domain", "geosite/amazon.mrs"),
    "ebay": _rp("ebay", "domain", "geosite/ebay.mrs"),
}

FULL_RULES = [
    "RULE-SET,category-ads-all,🛑 广告拦截",
    "RULE-SET,category-ai-chat-!cn,🤖 AI 服务",
    "RULE-SET,openai,🤖 AI 服务",
    "RULE-SET,anthropic,🤖 AI 服务",
    "RULE-SET,youtube,📹 油管视频",
    "RULE-SET,category-scholar-!cn,📚 教育学术",
    "RULE-SET,coursera,📚 教育学术",
    "RULE-SET,udemy,📚 教育学术",
    "RULE-SET,edx,📚 教育学术",
    "RULE-SET,khanacademy,📚 教育学术",
    "RULE-SET,wikimedia,📚 教育学术",
    "RULE-SET,aws,☁️ 云服务",
    "RULE-SET,azure,☁️ 云服务",
    "RULE-SET,cloudflare,☁️ 云服务",
    "RULE-SET,digitalocean,☁️ 云服务",
    "RULE-SET,vercel,☁️ 云服务",
    "RULE-SET,netlify,☁️ 云服务",
    "RULE-SET,cloudflare-ip,☁️ 云服务,no-resolve",
    "RULE-SET,google,🔍 谷歌服务",
    "RULE-SET,google-ip,🔍 谷歌服务,no-resolve",
    "RULE-SET,private,🏠 私有网络",
    "RULE-SET,private-ip,🏠 私有网络,no-resolve",
    "RULE-SET,geolocation-cn,🔒 国内服务",
    "RULE-SET,cn-ip,🔒 国内服务,no-resolve",
    "RULE-SET,telegram,📲 电报消息",
    "RULE-SET,telegram-ip,📲 电报消息,no-resolve",
    "RULE-SET,github,🐱 代码托管",
    "RULE-SET,gitlab,🐱 代码托管",
    "RULE-SET,atlassian,🐱 代码托管",
    "RULE-SET,microsoft,Ⓜ️ 微软服务",
    "RULE-SET,onedrive,Ⓜ️ 微软服务",
    "RULE-SET,apple-tvplus,📺 欧美流媒体",
    "RULE-SET,apple,🍏 苹果服务",
    "RULE-SET,icloud,🍏 苹果服务",
    "RULE-SET,twitter,🐦 推特/X",
    "RULE-SET,twitter-ip,🐦 推特/X,no-resolve",
    "RULE-SET,facebook,📘 Meta 系",
    "RULE-SET,instagram,📘 Meta 系",
    "RULE-SET,whatsapp,📘 Meta 系",
    "RULE-SET,facebook-ip,📘 Meta 系,no-resolve",
    "RULE-SET,discord,🎙️ Discord",
    "RULE-SET,tiktok,💬 其他社交",
    "RULE-SET,line,💬 其他社交",
    "RULE-SET,reddit,💬 其他社交",
    "RULE-SET,linkedin,💬 其他社交",
    "RULE-SET,snap,💬 其他社交",
    "RULE-SET,pinterest,💬 其他社交",
    "RULE-SET,tumblr,💬 其他社交",
    "RULE-SET,netflix,🎬 奈飞",
    "RULE-SET,netflix-ip,🎬 奈飞,no-resolve",
    "RULE-SET,disney,🏰 迪士尼+",
    "RULE-SET,hbo,📺 欧美流媒体",
    "RULE-SET,hulu,📺 欧美流媒体",
    "RULE-SET,primevideo,📺 欧美流媒体",
    "RULE-SET,spotify,📺 欧美流媒体",
    "RULE-SET,twitch,📺 欧美流媒体",
    "RULE-SET,dazn,📺 欧美流媒体",
    "RULE-SET,bahamut,🎌 亚洲流媒体",
    "RULE-SET,biliintl,🎌 亚洲流媒体",
    "RULE-SET,niconico,🎌 亚洲流媒体",
    "RULE-SET,abema,🎌 亚洲流媒体",
    "RULE-SET,viu,🎌 亚洲流媒体",
    "RULE-SET,kktv,🎌 亚洲流媒体",
    "RULE-SET,steam,🎮 Steam",
    "RULE-SET,epicgames,🖥️ PC 游戏",
    "RULE-SET,ea,🖥️ PC 游戏",
    "RULE-SET,ubisoft,🖥️ PC 游戏",
    "RULE-SET,blizzard,🖥️ PC 游戏",
    "RULE-SET,gog,🖥️ PC 游戏",
    "RULE-SET,riot,🖥️ PC 游戏",
    "RULE-SET,playstation,🎯 主机游戏",
    "RULE-SET,xbox,🎯 主机游戏",
    "RULE-SET,nintendo,🎯 主机游戏",
    "RULE-SET,docker,🛠️ 开发工具",
    "RULE-SET,npmjs,🛠️ 开发工具",
    "RULE-SET,jetbrains,🛠️ 开发工具",
    "RULE-SET,stackexchange,🛠️ 开发工具",
    "RULE-SET,dropbox,💾 网盘存储",
    "RULE-SET,notion,💾 网盘存储",
    "RULE-SET,paypal,💳 支付平台",
    "RULE-SET,stripe,💳 支付平台",
    "RULE-SET,wise,💳 支付平台",
    "RULE-SET,binance,₿ 加密货币",
    "RULE-SET,bbc,📰 新闻资讯",
    "RULE-SET,cnn,📰 新闻资讯",
    "RULE-SET,nytimes,📰 新闻资讯",
    "RULE-SET,wsj,📰 新闻资讯",
    "RULE-SET,bloomberg,📰 新闻资讯",
    "RULE-SET,amazon,🛒 海淘购物",
    "RULE-SET,ebay,🛒 海淘购物",
    "RULE-SET,geolocation-!cn,🌍 非中国",
    "RULE-SET,cn,🔒 国内服务",
    "MATCH,🐟 漏网之鱼",
]

# ═══════════════════════════════════════════
# 汇总
# ═══════════════════════════════════════════
PRESETS: dict[str, dict] = {
    "精简版": {"proxy_groups": SIMPLE_GROUPS, "rule_providers": SIMPLE_RP, "rules": SIMPLE_RULES},
    "标准版": {"proxy_groups": STANDARD_GROUPS, "rule_providers": STANDARD_RP, "rules": STANDARD_RULES},
    "完整版": {"proxy_groups": FULL_GROUPS, "rule_providers": FULL_RP, "rules": FULL_RULES},
}


def get_preset_names() -> list[str]:
    return list(PRESETS.keys())


def get_preset(name: str) -> dict | None:
    return PRESETS.get(name)
